### ISSUE TITLE
Having issues with manual adjustments

### ISSUE THREAD

**Issue by jlacadd** [rafaelmillan/ynab-multi-currency#1]
Hi Rafael!  Love the new product, it's really helping out with Cash transactions.  However, I do have an issue now that I've used it for a while.  My setup is Yen converted to Dollars.

Occasionally, I'll need to enter a literal dollar value in this account, for example when I do a reconciliation.  Is there a way to tell your app to ignore a transaction?  I've tried putting it in the past (before today), but it seems to still get converted.  Another example is withdrawals of cash from my dollar account into Yen.  In YNAB, this is a transfer, so the amount has to be same in both accounts.  But your app converts the value in the Cash account which results in changing the value in my checking account.  What is your app looking at to determine whether to go ahead and proceed with the conversion?  Is it the Yen(¥) symbol in the memo field?

Thanks!

**Comment by rafaelmillan** [comment]
Hi @jlacadd 

Good point, I didn't think of that use case.

At the moment you can skip conversion by adding `CX rate` to the memo. That will make the app think that the transaction has already been converted.

I will add the possibility to input a more user-friendly keyword such as `ignore` or `skip`. How does that sound?

Thanks for your feedback,
Rafael

**Comment by jlacadd** [comment]
That would be great!

**Comment by sean-wallace** [comment]
Would it be possible to detect which transactions are transfers from accounts in different currencies and if so adding a second transaction which corrects the balance?

**Comment by rafaelmillan** [comment]
@sean-wallace I opened a separate issue. I'll discuss it there https://github.com/rafaelmillan/ynab-multi-currency/issues/3

**Comment by rafaelmillan** [comment]
@sean-wallace You can now add the word `skip` any where in the memo if you don't want that transaction to be converted.
