### ISSUE TITLE
Allow to set custom currency rate

### ISSUE THREAD

**Issue by rafaelmillan** [rafaelmillan/ynab-multi-currency#10]
Message from a user:

>Is there any way we can set a custom currency rate? Living in Zimbabwe, we have USD and then we have an unofficial exchange rate for the local currency which changes, but which we would be able to update manually.

**Comment by andyclowe** [comment]
Very keen to have this functionality introduced. Apart from dealing with Countries where the local x-rate does not match that of the online providers, it could also be used for tracking other situations where a custom rate and currency might be needed.
