### ISSUE TITLE
Location of conversion notation in memo

### ISSUE THREAD

**Issue by sean-wallace** [rafaelmillan/ynab-multi-currency#2]
Hi Rafael,

Do you feel strongly about the location of the conversion notation? I'm finding it annoying that pre-existing memos are off to the right and I'm unable to see them. I've found myself manually editing the memos so that they read:

`{original_amount} {old_memo} (CX: X.XXX)`

but I'm not sure what is best.

Sean

**Comment by rafaelmillan** [comment]
Hi Sean,

I will add a setting so users can pick what they prefer.

Thanks,
Rafael

**Comment by rafaelmillan** [comment]
@sean-wallace The memo position can now be changed from the conversion edit page.

**Comment by sean-wallace** [comment]
This is great, thanks!
