### ISSUE TITLE
Long memo entry is truncated

### ISSUE THREAD

**Issue by sean-wallace** [rafaelmillan/ynab-multi-currency#5]
I noticed that memo entries are being truncated -- I imagine this is expected behavior, but it would be nice to have an option to disable it (or to control how many characters are allowed).

https://github.com/rafaelmillan/ynab-multi-currency/blob/1e5fa217ccac94a7b3e0b7bc88d1744abf417069/app/services/currency_converter.rb#L50

**Comment by rafaelmillan** [comment]
That's a YNAB limitation. Memos can't be longer than 50 characters.

There will always be some truncation, but I could add an option to pick a shorter Multi-Currency memo so there's more space for the original memo.

**Comment by sean-wallace** [comment]
Ah interesting, perhaps it's just an API limitation, because I appear to be able to manually enter a memo which is longer than 50 characters.

**Comment by rafaelmillan** [comment]
Good point. I'll ask YNAB if they can lift the API restriction.

**Comment by rafaelmillan** [comment]
I raised this to the Ynab team: https://support.youneedabudget.com/t/80bp6b

**Comment by sean-wallace** [comment]
I think this should be doable now?

Seen on YNAB's Release Notes page!
> Web Release Notes: May 14, 2019
API News
We’ve increased the max length of the memo field from 100 to 200 when creating or updating transactions. We’ve updated the docs accordingly (be sure to click ‘Model’ under the ‘data’ section).

**Comment by rafaelmillan** [comment]
@sean-wallace You're right. I update the truncation to 200 characters 🚀
