### ISSUE TITLE
Problem with transfer

### ISSUE THREAD

**Issue by sean-wallace** [rafaelmillan/ynab-multi-currency#6]
Hello again! I’m finding this tool very useful, thanks again for creating it. I keep finding little errors, I hope it’s not a problem that I post them here.

I entered a transfer between two foreign accounts, I entered the amount in foreign currency. When the add on converted that transaction to the budget currency, it removed the fact that it was a transfer, leaving a transaction with no payee and no category, which I then had to manually edit in YNAB to add that information back.

**Comment by rafaelmillan** [comment]
This has been fixed in https://github.com/rafaelmillan/ynab-multi-currency/commit/e9f27934f8770971c02d08bd93f1ec7cbc6b6185

**Comment by rafaelmillan** [comment]
This has been fixed in https://github.com/rafaelmillan/ynab-multi-currency/commit/608c572017ad5d208943dc56c5d70cba802b1b4d
