### ISSUE TITLE
Wrong conversions since November

### ISSUE THREAD

**Issue by jlacadd** [rafaelmillan/ynab-multi-currency#7]
Hi, just noticed this but confirmed it today.  Since around the beginning of November, the conversions have been incorrect.  I have been entering as I usually do, for example, yesterday a charge in JPY for 19,440 is entered as $194.40 USD.  Today, the value is $1.71 with the following memo:   ¥-195 (FX rate: 0.0087757).  It should have been around $170.86 USD.

I corrected all the older transactions to the best of my ability, but would appreciate it if this issue could be investigate soon or I'll have to disable this tool and go back to manual conversions.

BTW, I'll also be heading to UAE for a vacation for 2 weeks, so I'm planning to adjust my currency in use and keep using the same cash account.  Should be an interesting experiment.

**Comment by rafaelmillan** [comment]
Hi @jlacadd. There used to be a bug with currencies without sub-units (such as JPY and XOF) that I fixed early November. The correct behavior is that 19440 JPY should've been entered as 19440 USD. Entering 194.40 before November was a workaround to that bug. I suggest that from now on you start entering your foreign amounts with the point at the same place as the original currency. Does that make sense? Sorry for the confusion.

I used the add-on in a couple of holidays and it works great. What I usually do is I create a temporary cash account named "Cash (JPY)" and that's the one I setup for conversion. When the trip is over I just close the account.

**Comment by jlacadd** [comment]
Hmm...unfortunately that's a no-go for me.  If that sticks I'll have to disable this add-on.  For example, when I eat a typical lunch it's around 1000 yen.  If I have to enter that as $1000 and wait for it to get converted that completely blows my Dining category until it gets around to being converted.  Previously it was at least close to the actual $ amount.

**Comment by rafaelmillan** [comment]
@jlacadd I understand how that can throw off your budget, but that doesn't justify introducing a bug.

A solution would be to increase the frequency of conversions so your categories are not off for so long. Currently it's once a day. Would that help?

**Comment by jlacadd** [comment]
Understood, but unfortunately it removes too much of the convenience of the tool for me, which is the whole point of using it.  I can just as easily use the conversion tool on my phone to convert the transaction and enter the actual dollar amount.  Thanks for developing it, but I'm going to turn it off for now.  I'll keep tabs on it to see if there are any future features that can resolve this issue.

**Comment by rafaelmillan** [comment]
@jlacadd I added an "Offset" option to the conversion settings. This will multiply every pre-conversion amount by whatever number you set as the offset. I believe in your case you want that number to be 100.

Let me know if that works for you.

**Comment by jlacadd** [comment]
Wow thanks!  I think that will work!
