### ISSUE TITLE
"skip" keyword detection is case-sensitive

### ISSUE THREAD

**Issue by sean-wallace** [rafaelmillan/ynab-multi-currency#8]
When I enter transactions on my iPhone and add "skip" as the memo, it corrects the case to "Skip", which is not picked up correctly by the code. I believe the solution is just adding the `i` operator to the regex as below, but I haven't managed to get a working installation so am unable to test.

```
  def not_skipped?(transaction)
    /#{Regexp.quote(SKIP_KEYWORD)}/ie !~ transaction.memo
  end
```

**Comment by rafaelmillan** [comment]
Indeed. I corrected this in https://github.com/rafaelmillan/ynab-multi-currency/commit/d108f747820a82ca3ed13048889f3cfee0c965fd

Thanks for the fix!
