### ISSUE TITLE
Recent change introduced rounding

### ISSUE THREAD

**Issue by sean-wallace** [rafaelmillan/ynab-multi-currency#9]
I'm not sure what caused it, but recently my transactions seem to be rounded down before conversion. For example, a USD transaction of 25.75 is being rounded to 25, then converted to CAD with a memo like `US$25.00 (FX rate: 1.3203)`.

**Comment by sean-wallace** [comment]
I think this was introduced in 3e68cc6385215e9688f34fea566cafbc61aab3e0.

**Comment by rafaelmillan** [comment]
Thanks for the bug report. This should be fixed now.
